In [90]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
import seaborn as sns

In [91]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow import keras

df = pd.read_csv("C:/Users/user/Downloads/AI-class-test/PAMAP_features.csv", index_col=0)
df

sub_id  activity_id act_level     hr_mean  hr_mean_normal    hr_std  \
3006        2           17     light   87.000000        1.175676  0.000000   
3497        2            4  moderate  124.605469        1.683858  0.927920   
14495       7            5  vigorous  113.493430        1.891557  2.315888   
13278       7           17     light   82.513672        1.375228  0.492657   
14969       8            3     light   73.000000        1.106061  0.000000   
...       ...          ...       ...         ...             ...       ...   
10708       6            2     light   82.582031        1.376367  0.930285   
4870        3            2     light   76.998047        1.132324  0.806906   
11822       6            4  moderate   93.445312        1.557422  0.493415   
3866        2            7  moderate  129.160156        1.745408  0.361877   
3450        2           13  moderate  142.234375        1.922086  1.714464   

       hr_std_normal  hand_tmp_mean  hand_tmp_std  hand_acc_x_mean  ...  \
3006    7.105427e-15      34.375000      0.000000        -1.165524  ...   
3497    1.253946e-02      31.875000      0.000000       -12.040995  ...   
14495   3.859813e-02      32.500000      0.000000        -3.723040  ...   
13278   8.210948e-03      33.812500      0.000000        -3.618932  ...   
14969   7.327472e-15      34.437500      0.000000        -9.275877  ...   
...              ...            ...           ...              ...  ...   
10708   1.550475e-02      33.525635      0.030741        -4.306831  ...   
4870    1.186626e-02      32.083130      0.029390        -1.545991  ...   
11822   8.223580e-03      31.750000      0.000000       -10.034760  ...   
3866    4.890232e-03      30.465576      0.031088        -8.275569  ...   
3450    2.316843e-02      32.173340      0.026163        -3.077000  ...   

       ankle_acc_xz_cor  hand_gyr_xy_cor  hand_gyr_yz_cor  hand_gyr_xz_cor  \
3006           0.233251        -0.472662         0.335516        -0.377507   
3497          -0.119772        -0.287380        -0.230390        -0.491314   
14495          0.025673        -0.265566         0.824691        -0.121345   
13278          0.724061        -0.196728         0.315984        -0.380337   
14969         -0.001651        -0.060776         0.165672         0.311760   
...                 ...              ...              ...              ...   
10708          0.193950        -0.354026         0.175876        -0.172933   
4870           0.135629         0.056979         0.008235         0.001093   
11822         -0.404942         0.520845        -0.951838        -0.561901   
3866          -0.136336        -0.147614        -0.344375        -0.329746   
3450           0.200755        -0.081262         0.130816        -0.278256   

       chest_gyr_xy_cor  chest_gyr_yz_cor  chest_gyr_xz_cor  ankle_gyr_xy_cor  \
3006          -0.290138         -0.779952          0.071855         -0.305959   
3497           0.011124         -0.799319         -0.135736         -0.653133   
14495         -0.004923         -0.317761         -0.202148         -0.660278   
13278          0.284190         -0.109078         -0.071734         -0.177813   
14969         -0.272620         -0.014943         -0.191610         -0.261158   
...                 ...               ...               ...               ...   
10708          0.184131         -0.274344         -0.485489         -0.100010   
4870          -0.203294         -0.097797         -0.273316         -0.009717   
11822         -0.169119          0.299434         -0.100683         -0.555866   
3866          -0.024487         -0.536806         -0.161019         -0.752563   
3450          -0.254757         -0.723943         -0.039044         -0.016410   

       ankle_gyr_yz_cor  ankle_gyr_xz_cor  
3006          -0.003001         -0.638866  
3497          -0.654575          0.391363  
14495         -0.528138          0.402147  
13278          0.237828         -0.729771  
14969          0.066954          0.0576

In [92]:
df.columns

Index(['sub_id', 'activity_id', 'act_level', 'hr_mean', 'hr_mean_normal',
       'hr_std', 'hr_std_normal', 'hand_tmp_mean', 'hand_tmp_std',
       'hand_acc_x_mean', 'hand_acc_x_std', 'hand_acc_y_mean',
       'hand_acc_y_std', 'hand_acc_z_mean', 'hand_acc_z_std',
       'hand_gyr_x_mean', 'hand_gyr_x_std', 'hand_gyr_y_mean',
       'hand_gyr_y_std', 'hand_gyr_z_mean', 'hand_gyr_z_std', 'chest_tmp_mean',
       'chest_tmp_std', 'chest_acc_x_mean', 'chest_acc_x_std',
       'chest_acc_y_mean', 'chest_acc_y_std', 'chest_acc_z_mean',
       'chest_acc_z_std', 'chest_gyr_x_mean', 'chest_gyr_x_std',
       'chest_gyr_y_mean', 'chest_gyr_y_std', 'chest_gyr_z_mean',
       'chest_gyr_z_std', 'ankle_tmp_mean', 'ankle_tmp_std',
       'ankle_acc_x_mean', 'ankle_acc_x_std', 'ankle_acc_y_mean',
       'ankle_acc_y_std', 'ankle_acc_z_mean', 'ankle_acc_z_std',
       'ankle_gyr_x_mean', 'ankle_gyr_x_std', 'ankle_gyr_y_mean',
       'ankle_gyr_y_std', 'ankle_gyr_z_mean', 'ankle_gyr_z_std',
       '

In [93]:
# 결측치 확인
df.isnull().sum()

sub_id              0
activity_id         0
act_level           0
hr_mean             0
hr_mean_normal      0
                   ..
chest_gyr_yz_cor    0
chest_gyr_xz_cor    0
ankle_gyr_xy_cor    0
ankle_gyr_yz_cor    0
ankle_gyr_xz_cor    0
Length: 67, dtype: int64

In [94]:
# 결측치 제거
df = df.dropna()
df.isnull().sum()

sub_id              0
activity_id         0
act_level           0
hr_mean             0
hr_mean_normal      0
                   ..
chest_gyr_yz_cor    0
chest_gyr_xz_cor    0
ankle_gyr_xy_cor    0
ankle_gyr_yz_cor    0
ankle_gyr_xz_cor    0
Length: 67, dtype: int64

In [95]:
df['sub_id'].value_counts()

sub_id
5    1651
2    1618
8    1576
6    1556
1    1518
7    1430
4    1353
3    1042
9      29
Name: count, dtype: int64

In [96]:
df['activity_id'].value_counts()

activity_id
17    1539
4     1525
3     1220
1     1203
7     1196
2     1162
16    1099
6     1035
5      593
12     522
13     428
24     251
Name: count, dtype: int64

In [97]:
df['act_level'].value_counts()

act_level
moderate    5283
light       5124
vigorous    1366
Name: count, dtype: int64

In [98]:
df=df.drop(['sub_id', 'activity_id'],axis=1)

In [99]:
X=df.drop('act_level',axis=1)
X.head()

hr_mean  hr_mean_normal    hr_std  hr_std_normal  hand_tmp_mean  \
3006    87.000000        1.175676  0.000000   7.105427e-15        34.3750   
3497   124.605469        1.683858  0.927920   1.253946e-02        31.8750   
14495  113.493430        1.891557  2.315888   3.859813e-02        32.5000   
13278   82.513672        1.375228  0.492657   8.210948e-03        33.8125   
14969   73.000000        1.106061  0.000000   7.327472e-15        34.4375   

       hand_tmp_std  hand_acc_x_mean  hand_acc_x_std  hand_acc_y_mean  \
3006            0.0        -1.165524        2.383779         3.381285   
3497            0.0       -12.040995        3.734766         3.069947   
14495           0.0        -3.723040       10.188184        11.705779   
13278           0.0        -3.618932        1.935690         0.542981   
14969           0.0        -9.275877        0.082824         1.006239   

       hand_acc_y_std  ...  ankle_acc_xz_cor  hand_gyr_xy_cor  \
3006         2.582771  ...          0.233251        -0.472662   
3497         2.591651  ...         -0.119772        -0.287380   
14495       17.220389  ...          0.025673        -0.265566   
13278        2.907890  ...          0.724061        -0.196728   
14969        0.153816  ...         -0.001651        -0.060776   

       hand_gyr_yz_cor  hand_gyr_xz_cor  chest_gyr_xy_cor  chest_gyr_yz_cor  \
3006          0.335516        -0.377507         -0.290138         -0.779952   
3497         -0.230390        -0.491314          0.011124         -0.799319   
14495         0.824691        -0.121345         -0.004923         -0.317761   
13278         0.315984        -0.380337          0.284190         -0.109078   
14969         0.165672         0.311760         -0.272620         -0.014943   

       chest_gyr_xz_cor  ankle_gyr_xy_cor  ankle_gyr_yz_cor  ankle_gyr_xz_cor  
3006           0.071855         -0.305959         -0.003001         -0.638866  
3497          -0.135736         -0.653133         -0.654575          0.391363  
14495         -0.202148         -0.660278         -0.528138          0.402147  
13278         -0.071734         -0.177813          0.237828         -0.729771  
14969         -0.191610         -0.261158          0.066954          0.057685  

[5 rows x 64 columns]

In [100]:
y=df['act_level']
y.value_counts()

act_level
moderate    5283
light       5124
vigorous    1366
Name: count, dtype: int64

In [101]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.25,random_state=0)

In [102]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [103]:
# Build a logistic regression classifier and predict

clf_lr = LogisticRegression(random_state=0)
clf_lr.fit(X_train, y_train)

pred_lr = clf_lr.predict(X_test)

print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(y_test, pred_lr))
print (confusion_matrix(y_test, pred_lr))


--- Logistic Regression Classifier ---
0.9925271739130435
[[1245    5    0]
 [   6 1331    5]
 [   0    6  346]]


In [104]:
# Build a decision tree classifier and predict

clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(X_train, y_train)

pred_dt = clf_dt.predict(X_test)

print ("\n--- Decision Tree Classifier ---")
print (accuracy_score(y_test, pred_dt))
print (confusion_matrix(y_test, pred_dt))


--- Decision Tree Classifier ---
0.9891304347826086
[[1245    5    0]
 [  10 1325    7]
 [   0   10  342]]


In [105]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

print ("\n--- Random Forest ---")
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(X_train, y_train)
pred = rf_clf.predict(X_test)
print(accuracy_score(y_test,pred))
print (confusion_matrix(y_test, pred))


--- Random Forest ---
0.9972826086956522
[[1250    0    0]
 [   4 1338    0]
 [   0    4  348]]
